# Generated by Django 4.2.28 on 2026-08-14 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_booking', 'New Booking'), ('confirmed', 'Appointment Confirmed'), ('cancelled', 'Appointment Cancelled'), ('rescheduled', 'Rescheduled'), ('reminder', 'Reminder'), ('payment', 'Payment')], max_length=20),
        ),
    ]
